### ISSUE TITLE
setup() is broken

### ISSUE THREAD

**Issue by heiytor** [datsfilipe/min-theme.nvim#4]
According to the documentation, this should work.

```lua
require('min-theme').setup({ theme = 'light' })
```

However, I needed to change to:

```lua
require('min-theme').colorscheme()
```

Also, trying to call the setup before the colorscheme does not work either:

```lua
local theme = require('min-theme')

theme.setup({ theme = 'light' })
theme.colorscheme()
```

To change the theme to `min-theme-light`, the call needed to be:

```lua
vim.o.background = 'light'
require('min-theme').colorscheme()
```

**Comment by datsfilipe** [comment]
Hi! so the thing is:

- in order to have the light theme being defined by the `theme` option in the setup function, you cannot have `vim.o.background` option being set in your config, and the below line is presented as a comment in the readme:

**theme = 'dark', -- String: 'dark' or 'light', determines the colorscheme used (obs: if your config sets vim.o.background, this will do nothing)**

- `colorscheme` function is a helper to set the Neovim colorscheme as `min-theme`, it just uses `vim.cmd.colorscheme('min-theme')` under the hood
- the setup function should only configure the theme, in order to apply it you will always need to use the colorscheme function or manually set it as your colorscheme with `vim.cmd.colorscheme`

So check if, in your config, `vim.o.background` is being set anywhere else.

Note: That behavior is very common for Neovim colorschemes, but I think I will add this to the Readme anyways.

**Comment by datsfilipe** [comment]
I'm going to close it for now.
